### ISSUE TITLE
Phone not getting passed in during ticket creation?

### ISSUE THREAD

**Issue by karwalr** [dbasoftware/freshdesksharp#5]
I can see that the FreshdeskTicket object has a "Phone" property, but no matter what I pass into this, it doesn't seem to show up within the Freshdesk portal. Every other property such as Name, email, Subject etc all seem fine.

**Comment by karwalr** [comment]
Ignore me, it's an odd API as if you create a ticket for a user that already exists in the system as a contact, it does not update that users details. I solved this by getting the RequesterID from the CreateTicket response and then calling Contact.Update after this.  I'm not sure if there is a nicer way to chain this in to one request?

**Comment by fyndor** [comment]
I don't have a nice way to chain requests.  You just have to make separate requests sorry.
